name: Docker Base Auto Update CI

on:
  schedule:
    - cron: "23 13 3 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64,linux/armhf,linux/arm64

    steps:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
      - name: Docker Image Update Checker
        id: baseupdatecheck
=======
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - 
		name: Check if update available
        id: check
>>>>>>> parent of 795825c (Update auto-update-from-base-docker.yml)
=======
      - name: Docker Image Update Checker
        id: baseupdatecheck
>>>>>>> parent of 5cb79ee (Merge pull request #2 from origamiofficial/master)
=======
      - name: Docker Image Update Checker
        id: baseupdatecheck
>>>>>>> parent of e886e70 (Cleanup & add support for more platforms)
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/alpine:latest
          image: simeononsecurity/docker-vlmcsd:latest
      - name: Checkout
        uses: actions/checkout@v3
        if: steps.check.outputs.needs-updating == 'true'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
        if: steps.check.outputs.needs-updating == 'true'
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
        if: steps.check.outputs.needs-updating == 'true'
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: steps.check.outputs.needs-updating == 'true'
      - name: Build the Docker image
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes && docker buildx build --platform linux/amd64,linux/armhf,linux/arm64 -t simeononsecurity/docker-vlmcsd:latest --progress=plain --push .
        if: steps.check.outputs.needs-updating == 'true'
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
          tags: simeononsecurity/docker-vlmcsd:latest
        if: steps.check.outputs.needs-updating == 'true'
=======
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=registry,ref=simeononsecurity/docker-vlmcsd:buildcache
          cache-to: |
            type=registry,ref=simeononsecurity/docker-vlmcsd:buildcache,mode=max
>>>>>>> parent of 795825c (Update auto-update-from-base-docker.yml)
=======
          tags: simeononsecurity/docker-vlmcsd:latest
        if: steps.check.outputs.needs-updating == 'true'
>>>>>>> parent of 5cb79ee (Merge pull request #2 from origamiofficial/master)
=======
          tags: simeononsecurity/docker-vlmcsd:latest
        if: steps.check.outputs.needs-updating == 'true'
>>>>>>> parent of e886e70 (Cleanup & add support for more platforms)
