name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v7, linux/arm/v6, linux/386]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ matrix.platform }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          tags: |
            simeononsecurity/docker-vlmcsd:latest
            ghcr.io/simeononsecurity/docker-vlmcsd:latest
            - name: Create and push Docker manifest
            run: |
              docker manifest create simeononsecurity/docker-vlmcsd:latest \
                --amend ghcr.io/simeononsecurity/docker-vlmcsd:latest \
                --amend simeononsecurity/docker-vlmcsd:latest \
                --amend simeononsecurity/docker-vlmcsd:latest-arm64 \
                --amend simeononsecurity/docker-vlmcsd:latest-armv7 \
                --amend simeononsecurity/docker-vlmcsd:latest-armv6 \
                --amend simeononsecurity/docker-vlmcsd:latest-386
    
              docker manifest push simeononsecurity/docker-vlmcsd:latest
    
              # Push manifest to GitHub Container Registry
              docker manifest create ghcr.io/simeononsecurity/docker-vlmcsd:latest \
                --amend ghcr.io/simeononsecurity/docker-vlmcsd:latest \
                --amend simeononsecurity/docker-vlmcsd:latest \
                --amend simeononsecurity/docker-vlmcsd:latest-arm64 \
                --amend simeononsecurity/docker-vlmcsd:latest-armv7 \
                --amend simeononsecurity/docker-vlmcsd:latest-armv6 \
                --amend simeononsecurity/docker-vlmcsd:latest-386
    
              docker manifest push ghcr.io/simeononsecurity/docker-vlmcsd:latest
    